carrito/src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductoRepository::class)]
class Producto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $nombre = null;

    #[ORM\Column(length: 100)]
    private ?string $Descripcion = null;

    #[ORM\Column(length: 50)]
    private ?string $Imagen = null;

    #[ORM\Column]
    private ?float $Precio = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->Descripcion;
    }

    public function setDescripcion(string $Descripcion): static
    {
        $this->Descripcion = $Descripcion;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->Imagen;
    }

    public function setImagen(string $Imagen): static
    {
        $this->Imagen = $Imagen;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->Precio;
    }

    public function setPrecio(float $Precio): static
    {
        $this->Precio = $Precio;

        return $this;
    }
}

carrito/src/Controller/ProductoController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Producto;



class ProductoController extends AbstractController
{
 /**
 * @Route("/", name="listar_productos")
 */
 public function listarProductos(ManagerRegistry $doctrine): Response
 {
    $repository = $doctrine->getRepository(Producto::class);
    $productos = $repository->findAll();

    return $this->render('producto/lista.html.twig', ['productos' => $productos]);

 }

 /**
 * @Route("/producto/{id}", name="detalle_producto")
 */
public function detalleProducto(ManagerRegistry $doctrine, int $id): Response
{
   $repository = $doctrine->getRepository(Producto::class);
   $producto = $repository->find($id);

   if (!$producto) {
      throw $this->createNotFoundException('no existe');
   }

   return $this->render('producto/detalle.html.twig', ['productoDeta' => $producto]);

}

}


?>

carrito/templates/producto/detalle.html.twig
{% block body %}
<h1>Detalle de producto</h1>
<div class="detalles">

<div>
    <img src="{{ asset(productoDeta.imagen) }}" />
</div>
<br></br>
<div>
    <b>Producto {{productoDeta.id}}</b>
    <b>Lorem ipsum dolor sit amet</b>
        <b>Precio :  ${{productoDeta.precio}}</b>
        <a href="{{ path('listar_productos')}}">Volver</a>
</div>

</div>
{% endblock %}

carrito/templates/producto/lista.html.twig
{% extends 'base.html.twig' %}

{% block body %} 

{% include 'header.html.twig' %}
<div class = 'app'>



<h2>Lista Productos</h2>

<ul class = "lista">
{% for producto in productos %}
<li class="listap">
<div>
    <img  src="{{ asset(producto.imagen) }}" alt="{{ producto.nombre }}">
</div>
<div>
    <h1>Producto {{producto.nombre}}</h1>
    <p>Lorem ipsum es el texto que se usa habitualmente en diseño gráfico en demostraciones de tipografías o de 
    borradoresholaaaaa</p>
    <a href="{{ path('detalle_producto', {id: producto.id}) }}">Ver Detalles</a>
    <b>Precio : {{producto.precio}}</b>
</div>
</li>    
{% endfor %}
</ul>
</div>
{% endblock %}